# Generated by Django 4.1.4 on 2023-01-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=200)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_phone', models.CharField(max_length=10)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_gender', models.CharField(max_length=10)),
                ('emp_department', models.CharField(max_length=100)),
            ],
        ),
    ]
